#!/bin/bash
# Installer Cordova
npm install -g cordova

# Créer un projet
NOM_REPERTOIRE=cordova
ID_PROJET=io.cordova.cordova
NOM_AFFICHE_DE_L_APPLICATION="My cordova project"

cordova create $NOM_REPERTOIRE $ID_PROJET "$NOM_AFFICHE_DE_L_APPLICATION"

# Ajouter la plateforme android
cd $NOM_REPERTOIRE
cordova platform add android

# Déployer
cordova build
cordova build android

# Emuler un appareil Android
cordova emulate android

# Lancer l'application sur un appareil connecté
# cordova run android